name: 'Amplify-Init-Build-Deploy-Dev'
on:
  push:
    branches: [dev]
jobs:
  amplify-init-build-deploy:
    strategy:
      matrix:
        node_version: [12.x]
    name: Amplify Configure and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Install AWS CLI & Configure Profile
      env:
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:     ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run:  |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install

        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile default
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile default
        aws configure set default.region eu-west-2

    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}

    - name: Install Amplify CLI & Deploy Project
      run:  |
        set -x     
        npm install -g @aws-amplify/cli --unsafe-perm=true
        bash amplify_init_dev.sh
        # amplify env checkout devgithub
        # bash amplify_configure_dev.sh
        bash amplify_push_dev.sh
        amplify codegen

    - name: Commit Amplify Files
      uses: stefanzweifel/git-auto-commit-action@v4.2.0
      with:
        commit_message: Apply automatic changes
        file_pattern: . # amplify/* src/graphql/* # amplifyconfiguration.json awsconfiguration.json API
    




